name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggert nur bei Tags, die der Versionierung folgen (z. B. v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 21 (oder anpassen, falls eine andere Version benötigt wird)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the application
      - name: Build the application
        run: ./gradlew buildWithSpotlessAndShadowJar

      # Upload build artifacts for release
      - name: Upload release artifact
        id: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: true-connective-plugin
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download built artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: true-connective-plugin

      # Create a GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: build/libs/*.jar